from precautions import get_precautions
from severity import get_severity_score
from attacks import possible_attacks
from risk_reason import get_risk_reason


def generate_report(risk):
    """
    Generates a detailed cybersecurity risk report
    based on predicted risk level.
    """

    precautions = get_precautions(risk)
    severity = get_severity_score(risk)
    attacks = possible_attacks(risk)
    reason = get_risk_reason(risk)

    report = f"""
CYBERSECURITY RISK REPORT
========================

Risk Level       : {risk}
Severity Score   : {severity}/100

Risk Explanation
----------------
{reason}

Possible Cyber Attacks
----------------------
"""

    for attack in attacks:
        report += f"- {attack}\n"

    report += """
Recommended Security Precautions
--------------------------------
"""

    for p in precautions:
        report += f"- {p}\n"

    report += """
General Security Advice
-----------------------
- Keep systems and software up to date
- Monitor logs and unusual activities
- Educate users about cyber threats
- Perform regular security audits

Report Generated By:
Cybersecurity Risk Detector (Offline ML System)
"""

    return report
